apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-myapp
namePrefix: dev-

helmCharts:
  - name: myapp
    releaseName: myapp
    version: 0.1.0
    chartPath: ../../helm/myapp
    valuesFiles:
      - values-dev.yaml
    includeCRDs: false
